---
- block:
  - name: Discover the latest version
    shell:
      curl https://api.github.com/repos/golang/go/git/refs/tags/ | egrep 'ref.*refs/tags/go([0-9.]+)",' | egrep -o "[0-9.]+" | sort -V | tail -n 1
    register: latest_release
    changed_when: False

  - name: Setting version from latest release
    set_fact:
      go_version: "{{ latest_release.stdout_lines[0] }}"
  when:
    - go_version is not defined

- name: Register the current Go version (if any)
  command: /usr/local/go/bin/go version
  ignore_errors: yes
  register: current_go_version
  changed_when: false

- name: Install Go
  include_tasks: install_go.yml
  when: current_go_version|failed or current_go_version.stdout != go_version_target

- name: Add the Go bin directory to the PATH environment variable for all users
  copy:
    src: go-bin.sh
    dest: /etc/profile.d

- name: Set GOPATH for all users
  copy:
    src: go-path.sh
    dest: /etc/profile.d
  when: set_go_path
